#!/bin/bash
set -eu -o pipefail

##
## ecLego3 v3.2404.01
## Copyright (C) 2019-2026 Chee-Hong WONG (Dr Chia-Lin Wei Laboratory)
##
## ecLego3 workflow component
##   generate subpopulations from the refined assemblies
##
## call by ecLego3.draft.and.refine.sh via the script generated by
##   ecLego3.pl initsubpop
## which writes the bash script 
##   ecLego3.step.generate.subpopulations.se<X>.dicn<Y>.ovlp<Z>.sh
## which invokes ecLego3.generate.subpop.sh for each refined subgraph assembly
##

export ECLEGO_PIPELINE_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
export ECLEGO_ROOT=$(dirname "${ECLEGO_PIPELINE_PATH}")

if command -v apptainer &> /dev/null; then
    export APPTAINER_BINDPATH=${ECLEGO_ROOT}
else
    export SINGULARITY_BINDPATH=${ECLEGO_ROOT}
fi

export FASTQ=${1}
export REFGENOME=${2}
export SUBGRAPHID=${3}
export REFINEDSUBGRAPHID=${4}
export UDFcov2CN=${5:-""}
export UDFSEEDEXT=${6:-""}
export UDFMINOVERLAP=${7:-""}
export MINSUPPORT=${8:-""}

export SEEDEXT=5000
export MINOVERLAP=$(expr ${SEEDEXT} \* 2)

export KMCTHREADS=20
export KMCMAXMEMORYGB=16
export MINKMERCOUNT=2
export MAXKMERCOUNT=100000
export MINIMAP2THREADS=16
export SAMTOOLSTHREADS=16
export FLYETHREADS=16
export FLYEMINOVERLAP=${MINOVERLAP}

export OUTPUTDIR="${FASTQ}-ecLegoV3"
[ ! -d "${OUTPUTDIR}" ] && mkdir -p "${OUTPUTDIR}"
export KMCTMPDIR="${OUTPUTDIR}/kmc_tmp"
[ ! -d "${KMCTMPDIR}" ] && mkdir -p "${KMCTMPDIR}"
export OUTPREFIX="${OUTPUTDIR}/$(basename ${FASTQ})"

export RESULTPREFIX=$(basename ${FASTQ})
export RESULTPREFIX=$(echo $RESULTPREFIX | sed 's?.fq.gz$\|.fastq.gz$\|.fq$\|.fastq$??')


# set up the command
export KMCCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc"
export KMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc_tools"
export THRESHOLDSCMD="perl ${ECLEGO_PIPELINE_PATH}/getThreshold.pl"
export MINIMAP2CMD="${ECLEGO_PIPELINE_PATH}/minimap2_2.24.sif minimap2"
export SAMTOOLSCMD="${ECLEGO_PIPELINE_PATH}/samtools_1.19.sif samtools"
export FLYECMD="${ECLEGO_PIPELINE_PATH}/flye_2.9.1.sif flye"

export ECLGKMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_suite_3.2.1.mod.sif kmc_tools"
export ECLEGO3SUBPOPCMD="perl ${ECLEGO_PIPELINE_PATH}/cgSubPop.pl"

export GENOMECOVERAGEBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif genomeCoverageBed"
export SORTBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif sortBed"
export BG2BWCMD="${ECLEGO_PIPELINE_PATH}/ucsc-bedgraphtobigwig_445.sif bedGraphToBigWig"


${THRESHOLDSCMD} ${OUTPREFIX}.hist
export $(${THRESHOLDSCMD} ${OUTPREFIX}.hist | grep -v '^#' | xargs)
#
if [[ -n "${UDFcov2CN}" ]]; then
    cov2cn_value=$(echo "${UDFcov2CN}" | bc)
    if [[ $cov2cn_value -gt 0 ]]; then
        echo "# Adjusting Cov2CN ${cov2CN} to user-defined value ${cov2cn_value}"
        cov2CN="${cov2cn_value}"
        covcn_value=$(expr ${cov2cn_value} / 2)
        echo "# Adjusting CovCN ${covCN} to user-defined value ${covcn_value}"
        covCN="${covcn_value}"
        echo "# Not adjusting the remaining coverage variables."
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable coverage threshold provided ${UDFcov2CN}"
        echo "#####"
    fi
fi

if [[ -n "${UDFSEEDEXT}" ]]; then
    seedext_value=$(echo "${UDFSEEDEXT}" | bc)
    if [[ $seedext_value -gt 0 ]]; then
        echo "# Adjusting seed extension ${SEEDEXT} to user-defined value ${seedext_value}"
        SEEDEXT="${seedext_value}"
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable seed extension provided ${UDFSEEDEXT}"
        echo "#####"
    fi
fi

if [[ -n "${UDFMINOVERLAP}" ]]; then
    minoverlap_value=$(echo "${UDFMINOVERLAP}" | bc)
    if [[ $minoverlap_value -gt 0 ]]; then
        MINOVERLAP=${minoverlap_value}
        echo "# Adjusting minimum overlap ${FLYEMINOVERLAP} accordingly to ${MINOVERLAP}"
        FLYEMINOVERLAP=${MINOVERLAP}
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable minimum overlap provided ${UDFMINOVERLAP}"
        echo "#####"
    fi
fi

export MINSUPPORT_PARAM=""
if [[ -n "${MINSUPPORT}" ]]; then
    minsupport_value=$(echo "${MINSUPPORT}" | bc)
    if [[ $minsupport_value -gt 0 ]]; then
        export MINSUPPORT_PARAM="--minsupport ${minsupport_value}"
    fi
fi

# report final values
echo "# Effective values ---"
echo "# cov2CN=${cov2CN}"
echo "# covCN=${covCN}"
echo "# SEEDEXT=${SEEDEXT}"
echo "# MINOVERLAP=${MINOVERLAP}"
echo "# FLYEMINOVERLAP=${FLYEMINOVERLAP}"
echo "# ---"

# ---
export CLLABEL=${RESULTPREFIX}.cn${cov2CN}
export SUBGRAPHLABEL=subgraph_${SUBGRAPHID}
export ASSEMBLYDIR=${OUTPREFIX}_candidate_assembly.ci${SEEDEXT}
export REFINEDIR="${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}"
export REFINEDASSEMBLYDIR="${REFINEDIR}/${RESULTPREFIX}.${SUBGRAPHLABEL}_candidate_assembly.ci${SEEDEXT}"
export REFINEDASSEMBLYSIEVEDDIR="${REFINEDIR}/${RESULTPREFIX}.${SUBGRAPHLABEL}_candidate_assembly.ci${SEEDEXT}/assembly_sieved_graphs"


export OVERVIEWXLSFILE=${RESULTPREFIX}.sG${SUBGRAPHID}.cn${cov2CN}.disjointcyclic.gv.min25kb.overview.xls
export VCFFILE=${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.raw.vcf


# 
echo $(date) Subpopulations related scripts generation STARTED
# --minsupport 2
# TODO: --minsupport any consideration? what's the default?
${ECLEGO3SUBPOPCMD} setup \
--assembly ${REFINEDASSEMBLYSIEVEDDIR}/${OVERVIEWXLSFILE} \
--vcf ${REFINEDIR}/${VCFFILE} \
--dicncov ${cov2CN} \
--subgraph ${SUBGRAPHID} \
--rsg ${REFINEDSUBGRAPHID} \
--genome ${REFGENOME} \
--sample ${RESULTPREFIX} \
--scriptPath ${ECLEGO_PIPELINE_PATH} \
${MINSUPPORT_PARAM}
chmod a+x ${REFINEDASSEMBLYSIEVEDDIR}/{setup,process,refine}.sh
echo $(date) Subpopulations related scripts generation ENDED


# generate circular genome for all subpopulations
echo $(date) Subpopulations circular genome generation STARTED
${REFINEDASSEMBLYSIEVEDDIR}/setup.sh 2>&1 | tee ${REFINEDASSEMBLYSIEVEDDIR}/setup.run.log
echo $(date) Subpopulations circular genome generation ENDED
echo
echo

# Circular Genomes mapping and structural variations calling
echo $(date) Subpopulations genome mapping and structural variations calling STARTED
${REFINEDASSEMBLYSIEVEDDIR}/process.sh 2>&1 | tee ${REFINEDASSEMBLYSIEVEDDIR}/process.run.log
echo $(date) Subpopulations genome mapping and structural variations calling ENDED
echo
echo

# generate different data files for visualization and downstream analysis
echo $(date) Visualization and downstream analysis data generation STARTED
${REFINEDASSEMBLYSIEVEDDIR}/refine.sh 2>&1 | tee ${REFINEDASSEMBLYSIEVEDDIR}/refine.run.log
echo $(date) Visualization and downstream analysis data generation ENDED
echo
echo
