#!/bin/bash
set -eu -o pipefail

##
## ecLego3 v3.2404.01
## Copyright (C) 2019-2026 Chee-Hong WONG (Dr Chia-Lin Wei Laboratory)
##
## ecLego3 workflow component
##   refine subgraphs from a draft assembly
##
## call by ecLego3.draft.and.refine.sh via the script generated by
##   ecLego3.pl initsubgraph --step refine
## which writes the bash script 
##   ecLego3.step.refine.se<X>.dicn<Y>.ovlp<Z>.sh
## which invokes ecLego3.refine.sh for each draft subgraph assembly
##

export ECLEGO_PIPELINE_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
export ECLEGO_ROOT=$(dirname "${ECLEGO_PIPELINE_PATH}")

if command -v apptainer &> /dev/null; then
    export APPTAINER_BINDPATH=${ECLEGO_ROOT}
else
    export SINGULARITY_BINDPATH=${ECLEGO_ROOT}
fi

export FASTQ=${1}
export REFGENOME=${2}
export SUBGRAPHID=${3}
export UDFcov2CN=${4:-""}
export UDFSEEDEXT=${5:-""}
export UDFMINOVERLAP=${6:-""}

export SEEDEXT=5000
export MINOVERLAP=$(expr ${SEEDEXT} \* 2)

export KMCTHREADS=20
export KMCMAXMEMORYGB=16
export MINKMERCOUNT=2
export MAXKMERCOUNT=100000
export MINIMAP2THREADS=16
export SAMTOOLSTHREADS=16
export FLYETHREADS=16
export FLYEMINOVERLAP=${MINOVERLAP}

export OUTPUTDIR="${FASTQ}-ecLegoV3"
[ ! -d "${OUTPUTDIR}" ] && mkdir -p "${OUTPUTDIR}"
export KMCTMPDIR="${OUTPUTDIR}/kmc_tmp"
[ ! -d "${KMCTMPDIR}" ] && mkdir -p "${KMCTMPDIR}"
export OUTPREFIX="${OUTPUTDIR}/$(basename ${FASTQ})"

export RESULTPREFIX=$(basename ${FASTQ})
export RESULTPREFIX=$(echo $RESULTPREFIX | sed 's?.fq.gz$\|.fastq.gz$\|.fq$\|.fastq$??')


# set up the command
export SEQTKCMD="${ECLEGO_PIPELINE_PATH}/seqtk_1.3.sif seqtk"
export KMCCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc"
export KMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc_tools"
export THRESHOLDSCMD="perl ${ECLEGO_PIPELINE_PATH}/getThreshold.pl"
export MINIMAP2CMD="${ECLEGO_PIPELINE_PATH}/minimap2_2.24.sif minimap2"
export SAMTOOLSCMD="${ECLEGO_PIPELINE_PATH}/samtools_1.19.sif samtools"
export FLYECMD="${ECLEGO_PIPELINE_PATH}/flye_2.9.1.sif flye"

export ECLGKMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_suite_3.2.1.mod.sif kmc_tools"
export ECLEGO3CMD="perl ${ECLEGO_PIPELINE_PATH}/ecLego3.pl"

export GENOMECOVERAGEBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif genomeCoverageBed"
export SORTBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif sortBed"
export BG2BWCMD="${ECLEGO_PIPELINE_PATH}/ucsc-bedgraphtobigwig_445.sif bedGraphToBigWig"


${THRESHOLDSCMD} ${OUTPREFIX}.hist
export $(${THRESHOLDSCMD} ${OUTPREFIX}.hist | grep -v '^#' | xargs)
#
if [[ -n "${UDFcov2CN}" ]]; then
    cov2cn_value=$(echo "${UDFcov2CN}" | bc)
    if [[ $cov2cn_value -gt 0 ]]; then
        echo "# Adjusting Cov2CN ${cov2CN} to user-defined value ${cov2cn_value}"
        cov2CN="${cov2cn_value}"
        covcn_value=$(expr ${cov2cn_value} / 2)
        echo "# Adjusting CovCN ${covCN} to user-defined value ${covcn_value}"
        covCN="${covcn_value}"
        echo "# Not adjusting the remaining coverage variables."
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable coverage threshold provided ${UDFcov2CN}"
        echo "#####"
    fi
fi

if [[ -n "${UDFSEEDEXT}" ]]; then
    seedext_value=$(echo "${UDFSEEDEXT}" | bc)
    if [[ $seedext_value -gt 0 ]]; then
        echo "# Adjusting seed extension ${SEEDEXT} to user-defined value ${seedext_value}"
        SEEDEXT="${seedext_value}"
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable seed extension provided ${UDFSEEDEXT}"
        echo "#####"
    fi
fi

if [[ -n "${UDFMINOVERLAP}" ]]; then
    minoverlap_value=$(echo "${UDFMINOVERLAP}" | bc)
    if [[ $minoverlap_value -gt 0 ]]; then
        MINOVERLAP=${minoverlap_value}
        echo "# Adjusting minimum overlap ${FLYEMINOVERLAP} accordingly to ${MINOVERLAP}"
        FLYEMINOVERLAP=${MINOVERLAP}
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable minimum overlap provided ${UDFMINOVERLAP}"
        echo "#####"
    fi
fi

# report final values
echo "# Effective values ---"
echo "# cov2CN=${cov2CN}"
echo "# covCN=${covCN}"
echo "# SEEDEXT=${SEEDEXT}"
echo "# MINOVERLAP=${MINOVERLAP}"
echo "# FLYEMINOVERLAP=${FLYEMINOVERLAP}"
echo "# ---"


# ---
export CLLABEL=${RESULTPREFIX}.cn${cov2CN}
export SUBGRAPHLABEL=subgraph_${SUBGRAPHID}
export ASSEMBLYDIR=${OUTPREFIX}_candidate_assembly.ci${SEEDEXT}
export REFINEDIR="${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}"
export REFINEDASSEMBLYDIR="${REFINEDIR}/${RESULTPREFIX}.${SUBGRAPHLABEL}_candidate_assembly.ci${SEEDEXT}"

# subgraph#${SUBGRAPHLABEL}
echo $(date) Edges preparation STARTED
${SEQTKCMD} subseq \
${ASSEMBLYDIR}/20-repeat/graph_before_rr.fasta \
${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.readids \
> ${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fasta
echo $(date) Edges preparation ENDED

# build the kmerdb
mkdir -p ${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}
# note -ci1
echo $(date) Edges K-mer construction STARTED
${KMCCMD} -k29 -m${KMCMAXMEMORYGB} -t${KMCTHREADS} -ci1 -cs${MAXKMERCOUNT} \
-fa ${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fasta \
${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL} \
${REFINEDIR}/
echo $(date) Edges K-mer construction ENDED

# let's get the reads that are for this subgraph?!
# TODO: to compress ${OUTPREFIX}.readamp.cn_${covCN}.fastq.rdc.t2tv2.cn3.fastq
echo $(date) Subgraph reads recovery STARTED
${ECLGKMCTOOLSCMD} -t12 filter \
${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL} \
-ci1 ${OUTPREFIX}.readamp.cn_${covCN}.fastq.rdc.t2tv2.cn3.fastq \
-fq -ci${SEEDEXT} ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fastq
echo $(date) Subgraph reads recovery ENDED

# cd ${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}
[ ! -z "${REFGENOME}" ] && [ -f "${REFGENOME}" ] && { 
echo $(date) Subgraph reads recovery mapping STARTED
(${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} \
"${REFGENOME}" \
${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fastq \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.bam
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.bam)
echo $(date) Subgraph reads recovery mapping ENDED ; \

export DSNAME=${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.bam ; \
export CNSCALE=$(awk -v DICNSCALE=${cov2CN} 'BEGIN{print 2/DICNSCALE}') ; \
echo $(date) Generating bedgraph for ${DSNAME}.. ; \
${GENOMECOVERAGEBEDCMD} -bg -split -scale ${CNSCALE} -ibam ${DSNAME} \
| ${SORTBEDCMD} -i - > ${DSNAME}.bg ; \
echo $(date) Generating bigwig for ${DSNAME}.. ; \
${BG2BWCMD} ${DSNAME}.bg ${REFGENOME}.fai ${DSNAME}.2cn_${cov2CN}.bw && rm ${DSNAME}.bg
echo $(date) Subgraph reads recovery coverage ENDED
}

# let's attempt to assemble once more if the extract reads do not show coverage drop!
echo $(date) de Novo subgraph assembly STARTED
${FLYECMD} --threads ${FLYETHREADS} --meta \
--nano-hq ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fastq \
--out-dir ${REFINEDASSEMBLYDIR} \
-m ${FLYEMINOVERLAP} ; \
echo $(date) de Novo subgraph assembly ENDED

#
# TODO: need to check and update the path of inputs and outputs
#
export OUTPREFIX=${RESULTPREFIX}.${SUBGRAPHLABEL} ; \
export RESULTPREFIX=${OUTPREFIX} ; \
export GRAPHFASTA=${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta ; \
[ ! -z "${REFGENOME}" ] && [ -f "${REFGENOME}" ] && [ -f "${GRAPHFASTA}" ] && { 
# graph_before_rr
echo $(date) Assembly graph_before_rr reference mapping STARTED
(${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} \
"${REFGENOME}" \
${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${OUTPREFIX}.candidates.ci${SEEDEXT}.graph_before_rr.bam ; \
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${OUTPREFIX}.candidates.ci${SEEDEXT}.graph_before_rr.bam ; \
export DSNAME=${REFINEDIR}/${OUTPREFIX}.candidates.ci${SEEDEXT}.graph_before_rr.bam ; \
export CNSCALE=$(awk -v DICNSCALE=${cov2CN} 'BEGIN{print 2/DICNSCALE}') ; \
echo $(date) Generating bedgraph for ${DSNAME}.. ; \
${GENOMECOVERAGEBEDCMD} -bg -split -scale ${CNSCALE} -ibam ${DSNAME} \
| ${SORTBEDCMD} -i - > ${DSNAME}.bg ; \
echo $(date) Generating bigwig for ${DSNAME}.. ; \
${BG2BWCMD} ${DSNAME}.bg ${REFGENOME}.fai ${DSNAME}.2cn_${cov2CN}.bw && rm ${DSNAME}.bg ; \
echo $(date) Done. ) ; \
echo $(date) Assembly graph_before_rr reference mapping COMPLETED ; \

# filtered+raw summary
echo $(date) ecDNAs summarizing STARTED ; \
${ECLEGO3CMD} \
sievegraph \
--gv ${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.gv \
--diploidcov ${cov2CN} \
--minlenkb 25 \
--oprefix ${REFINEDASSEMBLYDIR}/${RESULTPREFIX} \
--bam ${REFINEDIR}/${OUTPREFIX}.candidates.ci${SEEDEXT}.graph_before_rr.bam ; \
echo $(date) ecDNAs summarizing ENDED

}

echo $(date) Read-to-Edges mapping STARTED ; \
${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} -N 10 -p 0.5 -L -z 1000 \
${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta \
${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fastq \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam ; \
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam ; \
echo $(date) Read-to-Edges mapping ENDED
