#!/bin/bash
set -eu -o pipefail

##
## ecLego3 v3.2404.01
## Copyright (C) 2019-2026 Chee-Hong WONG (Dr Chia-Lin Wei Laboratory)
##
## ecLego3 workflow component
##   assess the refined assemblies
##
## call by ecLego3.draft.and.refine.sh via the script generated by
##   ecLego3.pl initsubgraph --step assess
## which writes the bash script 
##   ecLego3.step.assess.refined.se<X>.dicn<Y>.ovlp<Z>.sh
## which invokes ecLego3.assess.refined.sh for each refined subgraph assembly
##

export ECLEGO_PIPELINE_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
export ECLEGO_ROOT=$(dirname "${ECLEGO_PIPELINE_PATH}")

if command -v apptainer &> /dev/null; then
    export APPTAINER_BINDPATH=${ECLEGO_ROOT}
else
    export SINGULARITY_BINDPATH=${ECLEGO_ROOT}
fi

export FASTQ=${1}
export REFGENOME=${2}
export SUBGRAPHID=${3}
export UDFcov2CN=${4:-""}
export UDFSEEDEXT=${5:-""}
export UDFMINOVERLAP=${6:-""}

export SEEDEXT=5000
export MINOVERLAP=$(expr ${SEEDEXT} \* 2)

export KMCTHREADS=20
export KMCMAXMEMORYGB=16
export MINKMERCOUNT=2
export MAXKMERCOUNT=100000
export MINIMAP2THREADS=16
export SAMTOOLSTHREADS=16
export FLYETHREADS=16
export FLYEMINOVERLAP=${MINOVERLAP}

export OUTPUTDIR="${FASTQ}-ecLegoV3"
[ ! -d "${OUTPUTDIR}" ] && mkdir -p "${OUTPUTDIR}"
export KMCTMPDIR="${OUTPUTDIR}/kmc_tmp"
[ ! -d "${KMCTMPDIR}" ] && mkdir -p "${KMCTMPDIR}"
export OUTPREFIX="${OUTPUTDIR}/$(basename ${FASTQ})"

export RESULTPREFIX=$(basename ${FASTQ})
export RESULTPREFIX=$(echo $RESULTPREFIX | sed 's?.fq.gz$\|.fastq.gz$\|.fq$\|.fastq$??')


# set up the command
export KMCCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc"
export KMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_3.2.1.sif kmc_tools"
export THRESHOLDSCMD="perl ${ECLEGO_PIPELINE_PATH}/getThreshold.pl"
export MINIMAP2CMD="${ECLEGO_PIPELINE_PATH}/minimap2_2.24.sif minimap2"
export SAMTOOLSCMD="${ECLEGO_PIPELINE_PATH}/samtools_1.19.sif samtools"
export FLYECMD="${ECLEGO_PIPELINE_PATH}/flye_2.9.1.sif flye"

export ECLGKMCTOOLSCMD="${ECLEGO_PIPELINE_PATH}/kmc_suite_3.2.1.mod.sif kmc_tools"
export ECLEGO3CMD="perl ${ECLEGO_PIPELINE_PATH}/ecLego3.pl"

export GENOMECOVERAGEBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif genomeCoverageBed"
export SORTBEDCMD="${ECLEGO_PIPELINE_PATH}/bedtools_2.31.0.sif sortBed"
export BG2BWCMD="${ECLEGO_PIPELINE_PATH}/ucsc-bedgraphtobigwig_445.sif bedGraphToBigWig"

export BCFTOOLSCMD="${ECLEGO_PIPELINE_PATH}/bcftools_1.19.sif bcftools"
export SNIFFLESSCMD="${ECLEGO_PIPELINE_PATH}/sniffles_2.3.3.sif sniffles"

${THRESHOLDSCMD} ${OUTPREFIX}.hist
export $(${THRESHOLDSCMD} ${OUTPREFIX}.hist | grep -v '^#' | xargs)
#
if [[ -n "${UDFcov2CN}" ]]; then
    cov2cn_value=$(echo "${UDFcov2CN}" | bc)
    if [[ $cov2cn_value -gt 0 ]]; then
        echo "# Adjusting Cov2CN ${cov2CN} to user-defined value ${cov2cn_value}"
        cov2CN="${cov2cn_value}"
        covcn_value=$(expr ${cov2cn_value} / 2)
        echo "# Adjusting CovCN ${covCN} to user-defined value ${covcn_value}"
        covCN="${covcn_value}"
        echo "# Not adjusting the remaining coverage variables."
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable coverage threshold provided ${UDFcov2CN}"
        echo "#####"
    fi
fi

if [[ -n "${UDFSEEDEXT}" ]]; then
    seedext_value=$(echo "${UDFSEEDEXT}" | bc)
    if [[ $seedext_value -gt 0 ]]; then
        echo "# Adjusting seed extension ${SEEDEXT} to user-defined value ${seedext_value}"
        SEEDEXT="${seedext_value}"
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable seed extension provided ${UDFSEEDEXT}"
        echo "#####"
    fi
fi

if [[ -n "${UDFMINOVERLAP}" ]]; then
    minoverlap_value=$(echo "${UDFMINOVERLAP}" | bc)
    if [[ $minoverlap_value -gt 0 ]]; then
        MINOVERLAP=${minoverlap_value}
        echo "# Adjusting minimum overlap ${FLYEMINOVERLAP} accordingly to ${MINOVERLAP}"
        FLYEMINOVERLAP=${MINOVERLAP}
    else
        echo "#####"
        echo "# WARNING: Ignoring unusable minimum overlap provided ${UDFMINOVERLAP}"
        echo "#####"
    fi
fi

# report final values
echo "# Effective values ---"
echo "# cov2CN=${cov2CN}"
echo "# covCN=${covCN}"
echo "# SEEDEXT=${SEEDEXT}"
echo "# MINOVERLAP=${MINOVERLAP}"
echo "# FLYEMINOVERLAP=${FLYEMINOVERLAP}"
echo "# ---"


# ---
export CLLABEL=${RESULTPREFIX}.cn${cov2CN}
export SUBGRAPHLABEL=subgraph_${SUBGRAPHID}
export ASSEMBLYDIR=${OUTPREFIX}_candidate_assembly.ci${SEEDEXT}
export REFINEDIR="${ASSEMBLYDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}"
export REFINEDASSEMBLYDIR="${REFINEDIR}/${RESULTPREFIX}.${SUBGRAPHLABEL}_candidate_assembly.ci${SEEDEXT}"
export REFINEDASSEMBLYSIEVEDDIR="${REFINEDIR}/${RESULTPREFIX}.${SUBGRAPHLABEL}_candidate_assembly.ci${SEEDEXT}/assembly_sieved_graphs"


# get SA for LRs against graph_before_rr
echo $(date) Read-to-graph_before_rr split-read extraction STARTED ; \
${SAMTOOLSCMD} view -f 0x800 ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam \
| cut -f 1 | sort | uniq > ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.SA.readids
#
${SAMTOOLSCMD} view -b -N ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.SA.readids \
${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam \
> ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.SA.bam
${SAMTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.SA.bam
#
export DSNAME=${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.SA.bam ; \
export CNSCALE=$(awk -v DICNSCALE=${cov2CN} 'BEGIN{print 2/DICNSCALE}') ; \
echo $(date) Generating bedgraph for ${DSNAME}.. ; \
${GENOMECOVERAGEBEDCMD} -bg -split -scale ${CNSCALE} -ibam ${DSNAME} \
| ${SORTBEDCMD} -i - > ${DSNAME}.bg ; \
echo $(date) Generating bigwig for ${DSNAME}.. ; \
${SAMTOOLSCMD} faidx ${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta ; \
${BG2BWCMD} ${DSNAME}.bg ${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta.fai ${DSNAME}.2cn_${cov2CN}.bw && rm ${DSNAME}.bg ; \
echo $(date) Done.
#
echo $(date) Read-to-graph_before_rr split-read extraction ENDED


# - the assembly.fasta against T2Tv2
echo $(date) Assembly-to-Reference mapping STARTED ; \
${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} -N 10 -p 0.5 -L -z 1000 \
"${REFGENOME}" \
${REFINEDASSEMBLYDIR}/assembly.fasta \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.assembly.bam ; \
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.assembly.bam ; \
echo $(date) Assembly-to-Reference mapping ENDED

# - the LRs against the assembly.fasta
echo $(date) Read-to-Assembly mapping STARTED ; \
${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} -N 10 -p 0.5 -L -z 1000 \
${REFINEDASSEMBLYDIR}/assembly.fasta \
${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.fastq \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam ; \
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam ; \
echo $(date) Read-to-Assembly mapping ENDED

# get SA for LRs against assembly.fasta
echo $(date) Read-to-Assembly split-read extraction STARTED ; \
${SAMTOOLSCMD} view -f 0x800 ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam \
| cut -f 1 | sort | uniq > ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.SA.readids
#
${SAMTOOLSCMD} view -b -N ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.SA.readids \
${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam \
> ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.SA.bam
${SAMTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.SA.bam
#
export DSNAME=${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.SA.bam ; \
export CNSCALE=$(awk -v DICNSCALE=${cov2CN} 'BEGIN{print 2/DICNSCALE}') ; \
echo $(date) Generating bedgraph for ${DSNAME}.. ; \
${GENOMECOVERAGEBEDCMD} -bg -split -scale ${CNSCALE} -ibam ${DSNAME} \
| ${SORTBEDCMD} -i - > ${DSNAME}.bg ; \
echo $(date) Generating bigwig for ${DSNAME}.. ; \
${SAMTOOLSCMD} faidx ${REFINEDASSEMBLYDIR}/assembly.fasta ; \
${BG2BWCMD} ${DSNAME}.bg ${REFINEDASSEMBLYDIR}/assembly.fasta.fai ${DSNAME}.2cn_${cov2CN}.bw && rm ${DSNAME}.bg ; \
echo $(date) Done.
#
echo $(date) Read-to-Assembly split-read extraction ENDED


# - the edges against the assembly.fasta
echo $(date) Edges-to-Assembly mapping STARTED ; \
${MINIMAP2CMD} -ax map-ont -t ${MINIMAP2THREADS} -N 10 -p 0.5 -L -z 1000 \
${REFINEDASSEMBLYDIR}/assembly.fasta \
${REFINEDASSEMBLYDIR}/20-repeat/graph_before_rr.fasta \
| ${SAMTOOLSCMD} sort -O BAM -@4 -o ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.graph_before_rr.asref.assembly.bam ; \
${SAMTOOLSCMD} index -@${SAMTOOLSTHREADS} ${REFINEDIR}/${CLLABEL}.disjointcyclic.gv.${SUBGRAPHLABEL}.graph_before_rr.asref.assembly.bam ; \
echo $(date) Edges-to-Assembly mapping ENDED


# - SV on (LRs against the assembly.fasta)
echo $(date) Read-to-Assembly sv calling STARTED ; \
#
${SNIFFLESSCMD} \
--allow-overwrite \
--input ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam \
--vcf ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.pass.vcf
#
${BCFTOOLSCMD} view -Oz -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.pass.vcf.gz ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.pass.vcf
${BCFTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.pass.vcf.gz
#
${SNIFFLESSCMD} \
--qc-output-all --allow-overwrite \
--input ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam \
--vcf ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.raw.vcf
#
${BCFTOOLSCMD} view -Oz -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.raw.vcf.gz ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.raw.vcf
${BCFTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.assembly.bam.raw.vcf.gz
#
echo $(date) Read-to-Assembly sv calling ENDED


# - SV on (LRs against the graph_before_rr.fasta)
echo $(date) Read-to-Edges sv calling STARTED ; \
#
${SNIFFLESSCMD} \
--allow-overwrite \
--input ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam \
--vcf ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.pass.vcf
#
${BCFTOOLSCMD} view -Oz -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.pass.vcf.gz ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.pass.vcf
${BCFTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.pass.vcf.gz
#
${SNIFFLESSCMD} \
--qc-output-all --allow-overwrite \
--input ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam \
--vcf ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.raw.vcf
#
${BCFTOOLSCMD} view -Oz -o ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.raw.vcf.gz ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.raw.vcf
${BCFTOOLSCMD} index ${REFINEDIR}/${CLLABEL}.candidates.ci${SEEDEXT}.asref.graph_before_rr.bam.raw.vcf.gz
#
echo $(date) Read-to-Edges sv calling ENDED


# sieve the refined assembly
[ ! -d "${REFINEDASSEMBLYSIEVEDDIR}" ] && mkdir -p "${REFINEDASSEMBLYSIEVEDDIR}"
echo $(date) Refined ${SUBGRAPHLABEL} graphs sieving STARTED ; \
${ECLEGO3CMD} \
sievegraph \
--gv ${REFINEDASSEMBLYDIR}/assembly_graph.gv \
--diploidcov ${cov2CN} \
--minlenkb 25 \
--oprefix ${REFINEDASSEMBLYSIEVEDDIR}/${RESULTPREFIX}.sG${SUBGRAPHID} \
--bam ${REFINEDIR}/${RESULTPREFIX}.cn${cov2CN}.disjointcyclic.gv.${SUBGRAPHLABEL}.assembly.bam ; \
echo $(date) Refined ${SUBGRAPHLABEL} graphs sieving ENDED

